CREATE TABLE "users" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"email" text NOT NULL,"password_hash" text NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL,"password_changed_at" timestamptz);
CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email");
CREATE TABLE "courses" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"title" text NOT NULL,"created_by" uuid NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,"original_filename" text,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "videos" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"course_id" uuid NOT NULL REFERENCES "courses"("id") ON DELETE CASCADE,"source_row_number" integer NOT NULL,"source_video_id" text,"title" text NOT NULL,"bunny_url" text NOT NULL,"source_data" jsonb NOT NULL,"playlist_order" integer NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX "videos_course_source_row_unique" ON "videos" ("course_id","source_row_number");
CREATE TABLE "reviews" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"video_id" uuid NOT NULL REFERENCES "videos"("id") ON DELETE CASCADE,"reviewer_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,"note" text,"was_played" boolean DEFAULT false NOT NULL,"reviewed_at" timestamptz,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX "reviews_video_reviewer_unique" ON "reviews" ("video_id","reviewer_id");
CREATE TABLE "sessions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"token_hash" text NOT NULL,"user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,"expires_at" timestamptz NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX "sessions_token_hash_unique" ON "sessions" ("token_hash");
